### ISSUE TITLE
undefined function utf8_encode()

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#198]
mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined function utf8_encode() in /var/www/clients/client0/web1/web/include/inc_lib/default.inc.php:194
mod_fcgid: stderr: Stack trace:
mod_fcgid: stderr: #0 /var/www/clients/client0/web1/web/include/inc_lib/general.inc.php(210): mb_substr('d5e76b867fdbf50...', 0, 32)
mod_fcgid: stderr: #1 /var/www/clients/client0/web1/web/img/cmsimage.php(43): cut_ext('d5e76b867fdbf50...')

**Comment by q23** [comment]
This is because the php-xml package is missing in your php installation.
