### ISSUE TITLE
Custom Contentpart Fields

### ISSUE THREAD

**Issue by q23rs** [slackero/phpwcms#334]
Get an error when switching from custom fields back to other or regular Template

'Fatal error: Uncaught TypeError: htmlspecialchars(): Argument #1 ($string) must be of type string, array given in /include/inc_lib/default.inc.php:1339 Stack trace: #0 /include/inc_lib/default.inc.php(1339): htmlspecialchars() #1 /include/inc_tmpl/content/cnt31.inc.php(364): html() #2 /include/inc_tmpl/articlecontent.edit.tmpl.php(620): include_once('/usr/www/users/...') #3 /include/inc_lib/article.editcontent.inc.php(706): include('/usr/www/users/...') #4 /phpwcms.php(499): include('/usr/www/users/...') #5 {main} thrown in /include/inc_lib/default.inc.php on line 1339

**Comment by q23rs** [comment]
Let me check!

**Comment by q23rs** [comment]
Works like a charm. Thx a lot.
Closed.
