### ISSUE TITLE
Warning und Fatal Error nach Installation

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#351]
phpwcms 1.10

Wenn ich mich nach der Installation im BE einloggen möchte erhalte ich folgende Fehlermeldungen:

```
Warning: require(D:\MAMP\htdocs\xxx\include\vendor\composer/../phpstan/phpstan/bootstrap.php): Failed to open stream: No such file or directory in D:\MAMP\htdocs\xxx\include\vendor\composer\autoload_real.php on line 41

Fatal error: Uncaught Error: Failed opening required 'D:\MAMP\htdocs\xxx\include\vendor\composer/../phpstan/phpstan/bootstrap.php' (include_path='.;C:\php\pear') in D:\MAMP\htdocs\xxx\include\vendor\composer\autoload_real.php:41 Stack trace: #0 D:\MAMP\htdocs\xxx\include\vendor\composer\autoload_real.php(45): {closure}('9b38cf48e83f5d8...', 'D:\\MAMP\\htdocs\\...') #1 D:\MAMP\htdocs\xxx\include\vendor\autoload.php(25): ComposerAutoloaderInit27746412545f20b1dea83d7fa7c0a077::getLoader() #2 D:\MAMP\htdocs\xxx\include\inc_lib\default.inc.php(162): require_once('D:\\MAMP\\htdocs\\...') #3 D:\MAMP\htdocs\xxx\login.php(54): require_once('D:\\MAMP\\htdocs\\...') #4 {main} thrown in D:\MAMP\htdocs\xxx\include\vendor\composer\autoload_real.php on line 41
```

Scheinbar wird versucht, auf ein nicht existierendes Verzeichnis zuzugreifen, was die Fehler auslöst.
Jedenfalls finde ich kein Verzeichnis **/phpstan**

**Comment by slackero** [comment]
Dürfte gelöst sein, habe die Abhängigkeit entfernt

**Comment by uwe367** [comment]
Ja, läuft jetzt fehlerfrei. Danke.
